test coverage diff (#18)
* change coverage comment header

* use run id to download artifact for diff

* install pycobertura using pip

* remove unused code

* replace env with outputs

* write diff info even if fail_on_decrease false

* check fail_on_decrease true

* add validation and refactor coverage action inputs

* coverage 100%

* skip clang tidy installation on windows

* remove unused cache  step

diff --git a/.github/coverage/action.yml b/.github/coverage/action.yml
--- a/.github/coverage/action.yml
+++ b/.github/coverage/action.yml
@@ -8,21 +8,29 @@ inputs:
   path:
     description: Path to the Cobertura coverage XML report.
     required: false
+    default: .
+  report_name:
+    description: Filename of the Cobertura coverage XML report.
+    required: false
     default: coverage.xml
   artifact_name:
     description: Unique name of coverage artifact to upload/download.
     required: false
     default: coverage
-  threshold:
+  min:
     description: The minimum allowed coverage percentage, as a real number.
     required: false
     default: 0
-  fail:
+  fail_min:
     description: Fail the action when the minimum coverage was not met.
     required: false
     default: true
-  fail_on_decrease:
-    description: Fail the action when the coverage decrease
+  diff:
+    description: Load cobertura report from target branch and create diff report.
+    required: false
+    default: true
+  fail_diff_decrease:
+    description: Fail the action when the coverage decrease.
     required: false
     default: false
   publish:
@@ -30,34 +38,51 @@ inputs:
     required: false
     default: false
   comment_header:
-    description: Coverage comment header, diplayed on top of PR comment
+    description: Coverage comment header, diplayed on top of PR comment.
     required: false
-    default: ""
+    default: "## 🧪 Coverage Summary"
 
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: bash
+      run: |
+        if ${{ inputs.diff == 'true' && github.base_ref == ''}}; then
+          echo -e "\e[31mError:\e[0m"
+          echo "Diff requested, but base ref is empty, please use this action ONLY in pull requests"
+          exit 1
+        fi
+        if ${{ inputs.min < 0 || github.min > 100 }}; then
+          echo -e "\e[31mError:\e[0m"
+          echo "min value should be in range [0, 100], provided value ${{ inputs.min }}"
+          exit 1
+        fi
+        if ${{ inputs.diff == 'false' && inputs.fail_diff_decrease == 'true' }}; then
+          echo -e "\e[31mError:\e[0m"
+          echo "fail_diff_decrease set to 'true', but diff is set to 'false'"
+          exit 1
+        fi
     - name: Setup Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'
 
     - name: Install pycobertura
-      uses: insightsengineering/pip-action@v2
-      with:
-        packages: pycobertura==3.0.0
+      shell: bash
+      run: |
+        python -m pip install pycobertura==3.0.0
 
     - name: Generate text report
-      run: |
-        mkdir -p coverage-action
-        cp ${{ inputs.path }} coverage-action/
-        pycobertura show ${{ inputs.path }} --format markdown --output .coverage-output
-        cat .coverage-output
       shell: bash
+      run: |
+        pycobertura show ${{ inputs.path }}/${{ inputs.report_name }} --format markdown --output .coverage-output
+        cat .coverage-output
 
     - name: Get base branch last run id
-      if: ${{ github.base_ref != ''}}
       shell: bash
+      id: base-run-id
+      if: ${{ inputs.diff == 'true' }}
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
@@ -66,37 +91,39 @@ runs:
 
     - name: Download ${{github.base_ref}} cobertura artifact
       id: download-baseline-cobertura
-      if: ${{ github.base_ref != ''}}
+      if: ${{ inputs.diff == 'true' }}
       # if artifact not found, continue
       continue-on-error: true
       uses: actions/download-artifact@v4
       with:
         github-token: ${{ github.token }}
-        run-id: ${{env.TARGET_BRANCH_RUN_ID}}
+        run-id: ${{steps.base-run-id.outputs.TARGET_BRANCH_RUN_ID}}
         name: ${{inputs.artifact_name}}
         path: coverage-action/prev
 
     - name: Coverage - Upload artifact
+      if: ${{ inputs.diff == 'true' }}
       uses: actions/upload-artifact@v4
       with:
         name: ${{inputs.artifact_name}}
-        path: ${{inputs.path}}
+        path: ${{inputs.path}}/${{ inputs.report_name }}
 
     - name: Generate diff report
+      shell: bash
       id: gen-diff-report
-      if: ${{steps.download-baseline-cobertura.outcome != 'failure'}}
+      if: ${{inputs.diff == 'true' && steps.download-baseline-cobertura.outcome != 'failure'}}
       run: |
-        pycobertura diff --no-color --no-source --format markdown coverage-action/prev/coverage.xml ${{ inputs.path }} \
+        pycobertura diff --no-color --no-source --format markdown coverage-action/prev/coverage.xml ${{ inputs.path }}/${{ inputs.report_name }} \
         --output .coverage-output-diff && pycobertura_status=$? || pycobertura_status=$?
         echo "PYCOBERTURA_STATUS=$pycobertura_status" >> $GITHUB_OUTPUT
         if [ "$pycobertura_status" -eq 1 ]; then
-          echo "Pycobertura exception occurred."
+          echo "\e[31mPycobertura exception occurred.\e[0m"
           exit 1
         fi
         cat .coverage-output-diff
-      shell: bash
 
     - name: Get total coverage
+      id: total-coverage
       shell: python
       run: |
         # Get total coverage
@@ -140,9 +167,9 @@ runs:
             )
 
         total = parseTotal(lastLine)
-        with open(os.getenv('GITHUB_ENV'), 'a') as f:
+        with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
             f.write(f'TOTAL_COVERAGE={total:.2f}\n')
-        if "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" != "1" and "${{steps.download-baseline-cobertura.outcome}}" != "failure":
+        if "${{inputs.diff}}" == "true" and "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" != "1" and "${{steps.download-baseline-cobertura.outcome}}" != "failure":
             lastLineDiff = readLastLine('.coverage-output-diff')
             if lastLineDiff == "":
                 raise SystemExit(
@@ -150,7 +177,7 @@ runs:
                 )
 
             diffTotal = parseTotal(lastLineDiff)
-            with open(os.getenv('GITHUB_ENV'), 'a') as f:
+            with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
                 f.write(f'TOTAL_DIFF_COVERAGE={diffTotal:.2f}\n')
 
     - name: Prepare coverage comment
@@ -165,20 +192,20 @@ runs:
                 for line in coverageTable:
                     f.write(line)
             f.write("\n\n")
-            f.write("_Minimum allowed coverage is \`${{ inputs.threshold }}%\`_\n")
+            f.write("_Minimum allowed coverage is \`${{ inputs.min }}%\`_\n")
             f.write("\n\n")
-            if '${{ inputs.baseline_path }}' != '':
+            if "${{inputs.diff}}" == "true" and "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" != "1" and "${{steps.download-baseline-cobertura.outcome}}" != "failure":
                 f.write("### Coverage diff")
                 f.write("\n\n")
                 with open(".coverage-output-diff", "r") as coverageTable:
                     for line in coverageTable:
                         f.write(line)
                 f.write("\n\n")
-                if "${{ inputs.fail_on_decrease }}" == "true":
+                if "${{steps.download-baseline-cobertura.outcome}}" != "failure":
                     if "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" == "2":
-                        f.write("Code changes increased the number of uncovered lines in at least one file.\n")
+                        f.write("⚠ Code changes increased the number of uncovered lines in at least one file.\n")
                     if "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" == "3":
-                        f.write("Code changes introduced new uncovered statements despite overall coverage improvement.\n")
+                        f.write("🫤 Code changes introduced new uncovered statements despite overall coverage improvement.\n")
             f.write("\n\n")
             f.write(":recycle: This comment has been updated with latest results")
 
@@ -190,25 +217,27 @@ runs:
         header: ${{ inputs.comment_header }}
         path: .coverage-output-message
 
-    - name: Check threshold
-      if: contains(inputs.fail, 'true') && (fromJSON(env.TOTAL_COVERAGE) < inputs.threshold)
+    - name: Check min
       shell: bash
+      if: contains(inputs.fail_min, 'true') && (fromJSON(steps.total-coverage.outputs.TOTAL_COVERAGE) < inputs.min)
       run: |
-        echo "Total Coverage of ${{ env.TOTAL_COVERAGE }}% falls below minimum threshold of ${{inputs.threshold}}%"
+        echo -e "\e[31mError:\e[0m"
+        echo "Total Coverage of ${{ steps.total-coverage.outputs.TOTAL_COVERAGE }}% falls below minimum of ${{inputs.min}}%"
         exit 1
 
     - name: Check coverage decrease
-      if: ${{ inputs.baseline_path != '' && contains(inputs.fail_on_decrease, 'true') && (fromJSON(env.TOTAL_DIFF_COVERAGE) < 0) }}
       shell: bash
+      if: ${{ inputs.diff == 'true' && steps.download-baseline-cobertura.outcome != 'failure' && inputs.fail_diff_decrease == 'true' && (fromJSON(steps.total-coverage.outputs.TOTAL_DIFF_COVERAGE) < 0) }}
       run: |
-        echo "Total Coverage is decreased: ${{ env.TOTAL_DIFF_COVERAGE }}%"
-        if [[ "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" == "2" && "${{ inputs.fail_on_decrease }}" == "true" ]]
+        echo -e "\e[31mError:\e[0m"
+        echo "Total Coverage is decreased: ${{ steps.total-coverage.outputs.TOTAL_DIFF_COVERAGE }}%"
+        if [[ "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" == "2" ]]
         then {
           echo "Code changes increased the number of uncovered lines in at least one file."
           exit 1
         }
         fi
-        if [[ "${{ steps.gen-diff-report.outputs.pycobertura_status }}" == "3" && "${{ inputs.fail_on_decrease }}" == "true" ]]
+        if [[ "${{ steps.gen-diff-report.outputs.PYCOBERTURA_STATUS }}" == "3" ]]
         then {
           echo "Code changes introduced new uncovered statements despite overall coverage improvement."
           exit 1
@@ -217,9 +246,9 @@ runs:
         exit 1
 
     - name: Clean up intermediate files
+      shell: bash
       if: always()
       run: |
         rm -rf coverage-action .coverage-output \
           .coverage-output-diff \
           .coverage-output-diff-message
-      shell: bash
